### ISSUE TITLE
how to connect oracle database with sql developer?

### ISSUE THREAD

**Issue by shaheerakr** [Shaheer-Imam/Al-Mustafa-Jewellery-Point#4]

**Comment by Shaheer-Imam** [comment]
If you are using oracle 11g and have SQL Plus then run cmd as administrator and do the following steps
- type "sqlplus / as sysdba"
After connecting to oracle type the statement
- CREATE USER username IDENTIFIED BY password; 
 where username and password can be the schema and your password respectively
Then type the following statement to assign system priviliges
- GRANT create session TO username;
- GRANT create table TO username;
- GRANT create view TO username;
- GRANT create any trigger TO username;
- GRANT create any procedure TO username;
- GRANT create sequence TO username;
- GRANT create synonym TO username;

You will create a schema for your oracle database. After this open your sqldeveloper and click new connection and perform the following steps
- Choose a name for your database which can be any name you want
- Enter your schema name and password 
- Write the port number which is 1521 by default 
- Select SID as xe or orcl according to your system 
- Click connect
